version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: emilfrey
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: car_offer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
